BATCH4 = {
    "fenerbahce": ("Fenerbahçe", "Fenerbahçe", "Fenerbahçe", "#FFED00", "#0A3B77", r"fenerbah[çc]e"),
    "galatasaray": ("Galatasaray", "Galatasaray", "Galatasaray", "#E30613", "#FFD100", r"galatasaray"),
    "besiktas": ("Beşiktaş", "Beşiktaş", "Beşiktaş", "#000000", "#FFFFFF", r"be[sş]ikta[sş]"),
    "alnassr": ("Al-Nassr FC", "Al-Nassr FC", "Al-Nassr FC", "#FFF200", "#003DA5", r"al-nassr|al nassr"),
    "youngboys": ("BSC Young Boys", "BSC Young Boys", "BSC Young Boys", "#FFE500", "#000000", r"young boys"),
    "fccopenhagen": ("FC Copenhague", "FC Copenhagen", "FC Copenhaga", "#FFFFFF", "#DA291C", r"fc copenhag(ue|en|a)|f\.c\. copenhagen"),
    "realvalladolid": ("Real Valladolid", "Real Valladolid", "Real Valladolid", "#5C2D91", "#FFFFFF", r"real valladolid"),
    "stpauli": ("FC St. Pauli", "FC St. Pauli", "FC St. Pauli", "#6B4226", "#FFFFFF", r"st\.?\s*pauli"),
    "hullcity": ("Hull City", "Hull City", "Hull City", "#F5A623", "#000000", r"hull city"),
    "speziacalcio": ("Spezia Calcio", "Spezia Calcio", "Spezia Calcio", "#000000", "#FFFFFF", r"spezia calcio"),
    "fcmetz": ("FC Metz", "FC Metz", "FC Metz", "#7A1F2B", "#87CEEB", r"\bfc metz\b"),
    "asse": ("AS Saint-Étienne", "AS Saint-Étienne", "AS Saint-Étienne", "#00A651", "#FFFFFF", r"\basse\b|saint-[ée]tienne"),
    "guingamp": ("EA Guingamp", "EA Guingamp", "EA Guingamp", "#E4002B", "#000000", r"guingamp"),
    "redstarfc": ("Red Star FC", "Red Star FC", "Red Star FC", "#E4002B", "#FFFFFF", r"red star fc"),
    "estunis": ("ES Tunis", "ES Tunis", "ES Tunis", "#E4002B", "#FFD700", r"\bes tunis\b|esp[ée]rance.{0,3}tunis"),
    "jskabylie": ("JS Kabylie", "JS Kabylie", "JS Kabylie", "#FFD700", "#006233", r"js kabylie"),
    "versailles78": ("FC Versailles 78", "FC Versailles 78", "FC Versailles 78", "#00843D", "#FFFFFF", r"versailles 78"),
    "kallithea": ("GS Kallithéa", "GS Kallithea", "GS Kallithéa", "#0057B7", "#87CEEB", r"kallith[ée]a"),
    "wydad": ("Wydad AC", "Wydad AC", "Wydad AC", "#E4002B", "#FFFFFF", r"wydad"),
    "seattlesounders": ("Seattle Sounders", "Seattle Sounders", "Seattle Sounders", "#5D9732", "#0033A0", r"seattle sounders"),
}
