# key: (name_es, name_en, name_pt, color1, color2, pattern_hint_regex)
BATCH1 = {
    # Premier League
    "arsenal": ("Arsenal", "Arsenal", "Arsenal", "#EF0107", "#FFFFFF", r"\barsenal\b"),
    "astonvilla": ("Aston Villa", "Aston Villa", "Aston Villa", "#95BFE5", "#670E36", r"aston villa"),
    "bournemouth": ("Bournemouth", "Bournemouth", "Bournemouth", "#DA291C", "#000000", r"\bbournemouth\b"),
    "brentford": ("Brentford", "Brentford", "Brentford", "#E30613", "#FFFFFF", r"\bbrentford\b"),
    "brighton": ("Brighton", "Brighton", "Brighton", "#0057B8", "#FFFFFF", r"\bbrighton\b"),
    "crystalpalace": ("Crystal Palace", "Crystal Palace", "Crystal Palace", "#1B458F", "#C4122E", r"crystal palace"),
    "everton": ("Everton", "Everton", "Everton", "#003399", "#FFFFFF", r"\beverton\b"),
    "fulham": ("Fulham", "Fulham", "Fulham", "#FFFFFF", "#000000", r"\bfulham\b"),
    "leeds": ("Leeds United", "Leeds United", "Leeds United", "#FFFFFF", "#1D428A", r"leeds united"),
    "mancity": ("Manchester City", "Manchester City", "Manchester City", "#6CABDD", "#1C2C5B", r"manchester city"),
    "newcastle": ("Newcastle United", "Newcastle United", "Newcastle United", "#241F20", "#FFFFFF", r"newcastle"),
    "nottinghamforest": ("Nottingham Forest", "Nottingham Forest", "Nottingham Forest", "#DD0000", "#FFFFFF", r"nottingham forest"),
    "sunderland": ("Sunderland", "Sunderland", "Sunderland", "#EB172B", "#FFFFFF", r"\bsunderland\b"),
    "tottenham": ("Tottenham Hotspur", "Tottenham Hotspur", "Tottenham Hotspur", "#FFFFFF", "#132257", r"tottenham"),
    "westham": ("West Ham United", "West Ham United", "West Ham United", "#7A263A", "#1BB1E7", r"west ham"),
    "wolves": ("Wolverhampton Wanderers", "Wolverhampton Wanderers", "Wolverhampton Wanderers", "#FDB913", "#231F20", r"wolverhampton|\bwolves\b"),
    # La Liga
    "atleticomadrid": ("Atlético de Madrid", "Atlético Madrid", "Atlético de Madrid", "#CE3524", "#FFFFFF", r"atl[eé]tico de madrid|atl[eé]tico madrid|\bcholo\b"),
    "athleticbilbao": ("Athletic Club", "Athletic Bilbao", "Athletic Bilbao", "#EE2523", "#FFFFFF", r"athletic (club|bilbao)"),
    "realsociedad": ("Real Sociedad", "Real Sociedad", "Real Sociedad", "#0067B1", "#FFFFFF", r"real sociedad"),
    "realbetis": ("Real Betis", "Real Betis", "Real Betis", "#00954C", "#FFFFFF", r"real betis|betis balompi[eé]"),
    "villarreal": ("Villarreal", "Villarreal", "Villarreal", "#FFE667", "#005187", r"\bvillarreal\b"),
    "valencia": ("Valencia CF", "Valencia CF", "Valencia CF", "#FFFFFF", "#EE3524", r"valencia cf|valencia c\.f"),
    "sevilla": ("Sevilla FC", "Sevilla FC", "Sevilla FC", "#FFFFFF", "#D2001C", r"\bsevilla\b"),
    "celtavigo": ("Celta de Vigo", "Celta Vigo", "Celta de Vigo", "#8AC3EE", "#FFFFFF", r"celta de vigo|celta vigo"),
    "girona": ("Girona FC", "Girona FC", "Girona FC", "#CB1120", "#FFFFFF", r"\bgirona\b"),
    "osasuna": ("Osasuna", "Osasuna", "Osasuna", "#D2001C", "#001A4B", r"\bosasuna\b"),
    "rayovallecano": ("Rayo Vallecano", "Rayo Vallecano", "Rayo Vallecano", "#FFFFFF", "#E4022D", r"rayo vallecano"),
    "getafe": ("Getafe CF", "Getafe CF", "Getafe CF", "#005CA9", "#FFFFFF", r"\bgetafe\b"),
    "mallorca": ("RCD Mallorca", "RCD Mallorca", "RCD Mallorca", "#CB0526", "#000000", r"\bmallorca\b"),
    "alaves": ("Deportivo Alavés", "Deportivo Alavés", "Deportivo Alavés", "#0F4DA1", "#FFFFFF", r"alav[eé]s"),
    "espanyol": ("RCD Espanyol", "RCD Espanyol", "RCD Espanyol", "#0A3F91", "#FFFFFF", r"\bespanyol\b"),
    "levante": ("Levante UD", "Levante UD", "Levante UD", "#0044A0", "#B4122A", r"\blevante\b"),
    "elche": ("Elche CF", "Elche CF", "Elche CF", "#00A650", "#FFFFFF", r"\belche\b"),
    "realoviedo": ("Real Oviedo", "Real Oviedo", "Real Oviedo", "#0B4EA2", "#FFFFFF", r"real oviedo"),
    # Serie A
    "intermilan": ("Inter de Milán", "Inter Milan", "Inter de Milão", "#010E80", "#000000", r"\binter (de )?milan\b|internazionale"),
    "acmilan": ("AC Milan", "AC Milan", "AC Milan", "#FB090B", "#000000", r"\b(ac )?milan\b"),
    "napoli": ("Napoli", "Napoli", "Nápoles", "#12A0D7", "#FFFFFF", r"\bnapoli\b"),
    "roma": ("AS Roma", "AS Roma", "AS Roma", "#8E1F2F", "#F0BC42", r"\bas roma\b|\broma\b"),
    "lazio": ("Lazio", "Lazio", "Lazio", "#87D8F7", "#FFFFFF", r"\blazio\b"),
    "atalanta": ("Atalanta", "Atalanta", "Atalanta", "#1E71B8", "#000000", r"\batalanta\b"),
    "fiorentina": ("Fiorentina", "Fiorentina", "Fiorentina", "#642F8E", "#FFFFFF", r"\bfiorentina\b"),
    "bologna": ("Bologna", "Bologna", "Bolonha", "#A61B22", "#1A2F42", r"\bbologna\b"),
    "torino": ("Torino", "Torino", "Torino", "#881D1E", "#FFFFFF", r"\btorino\b"),
    "udinese": ("Udinese", "Udinese", "Udinese", "#000000", "#FFFFFF", r"\budinese\b"),
    # Bundesliga
    "dortmund": ("Borussia Dortmund", "Borussia Dortmund", "Borussia Dortmund", "#FDE100", "#000000", r"borussia dortmund|\bbvb\b"),
    "rbleipzig": ("RB Leipzig", "RB Leipzig", "RB Leipzig", "#DD0741", "#FFFFFF", r"rb leipzig"),
    "leverkusen": ("Bayer Leverkusen", "Bayer Leverkusen", "Bayer Leverkusen", "#E32221", "#000000", r"bayer leverkusen"),
    "frankfurt": ("Eintracht Frankfurt", "Eintracht Frankfurt", "Eintracht Frankfurt", "#E1000F", "#000000", r"eintracht frankfurt"),
    "gladbach": ("Borussia Mönchengladbach", "Borussia Mönchengladbach", "Borussia Mönchengladbach", "#000000", "#FFFFFF", r"m[oö]nchengladbach"),
    "stuttgart": ("VfB Stuttgart", "VfB Stuttgart", "VfB Stuttgart", "#E32219", "#FFFFFF", r"vfb stuttgart"),
    "wolfsburg": ("VfL Wolfsburg", "VfL Wolfsburg", "VfL Wolfsburg", "#65B32E", "#FFFFFF", r"wolfsburg"),
    # Ligue 1
    "marseille": ("Olympique de Marsella", "Olympique de Marseille", "Olympique de Marselha", "#2FAEE0", "#FFFFFF", r"marseille|\bom\b"),
    "monaco": ("AS Mónaco", "AS Monaco", "AS Mônaco", "#E51B22", "#FFFFFF", r"\bmonaco\b"),
    "lyon": ("Olympique de Lyon", "Olympique Lyonnais", "Olympique de Lyon", "#DA1D27", "#00338D", r"\blyon\b|olympique lyonnais"),
    "lille": ("LOSC Lille", "LOSC Lille", "LOSC Lille", "#E0122A", "#004A94", r"\blille\b"),
    "nice": ("OGC Nice", "OGC Nice", "OGC Nice", "#CC0000", "#000000", r"\bnice\b"),
    "rennes": ("Stade Rennais", "Stade Rennes", "Stade Rennes", "#E2001A", "#000000", r"\brennes\b"),
}

CATEGORY = {k: "club" for k in BATCH1}
