BATCH2 = {
    # Bundesliga remaining
    "werderbremen": ("Werder Bremen", "Werder Bremen", "Werder Bremen", "#1D9053", "#FFFFFF", r"werder bremen"),
    "freiburg": ("SC Freiburg", "SC Freiburg", "SC Freiburg", "#000000", "#FFFFFF", r"\bfreiburg\b"),
    "unionberlin": ("Union Berlin", "Union Berlin", "Union Berlin", "#EB1923", "#FFFFFF", r"union berlin"),
    "mainz": ("Mainz 05", "Mainz 05", "Mainz 05", "#C3141E", "#FFFFFF", r"\bmainz\b"),
    "augsburg": ("FC Augsburg", "FC Augsburg", "FC Augsburg", "#BA3733", "#FFFFFF", r"\baugsburg\b"),
    "hoffenheim": ("TSG Hoffenheim", "TSG Hoffenheim", "TSG Hoffenheim", "#1961B5", "#FFFFFF", r"\bhoffenheim\b"),
    "koln": ("1. FC Köln", "1. FC Köln", "1. FC Köln", "#ED1C24", "#FFFFFF", r"\bk[oö]ln\b|fc cologne"),
    "hamburg": ("Hamburger SV", "Hamburger SV", "Hamburger SV", "#0D1A5C", "#FFFFFF", r"hamburger sv|\bhsv\b"),
    # Ligue 1 remaining
    "lens": ("RC Lens", "RC Lens", "RC Lens", "#FFED00", "#C8102E", r"\blens\b"),
    "strasbourg": ("RC Strasbourg", "RC Strasbourg", "RC Strasbourg", "#0072CE", "#FFFFFF", r"strasbourg"),
    "toulouse": ("Toulouse FC", "Toulouse FC", "Toulouse FC", "#5B2A86", "#FFFFFF", r"\btoulouse\b"),
    "nantes": ("FC Nantes", "FC Nantes", "FC Nantes", "#FFDD00", "#1B7B3E", r"\bnantes\b"),
    "brest": ("Stade Brestois", "Stade Brestois", "Stade Brestois", "#DA1F3D", "#FFFFFF", r"\bbrest\b"),
    "reims": ("Stade de Reims", "Stade de Reims", "Stade de Reims", "#E2001A", "#FFFFFF", r"\breims\b"),
    # National teams
    "belgica": ("Bélgica", "Belgium", "Bélgica", "#ED2939", "#FFD90C", r"\bb[eé]lgica\b|\bbelgium\b|\bbelgique\b"),
    "dinamarca": ("Dinamarca", "Denmark", "Dinamarca", "#C60C30", "#FFFFFF", r"\bdinamarca\b|\bdenmark\b|\bdanemark\b"),
    "suiza": ("Suiza", "Switzerland", "Suíça", "#FF0000", "#FFFFFF", r"\bsuiza\b|\bswitzerland\b|\bsuisse\b|\bsu[ií]ça\b"),
    "polonia": ("Polonia", "Poland", "Polônia", "#DC143C", "#FFFFFF", r"\bpolonia\b|\bpoland\b|\bpologne\b|\bpol[oô]nia\b"),
    "gales": ("Gales", "Wales", "País de Gales", "#C8102E", "#FFFFFF", r"\bgales\b|\bwales\b|\bpays de galles\b"),
    "escocia": ("Escocia", "Scotland", "Escócia", "#0065BD", "#FFFFFF", r"\bescocia\b|\bscotland\b|\b[eé]cosse\b|\besc[oó]cia\b"),
    "suecia": ("Suecia", "Sweden", "Suécia", "#006AA7", "#FECC02", r"\bsuecia\b|\bsweden\b|\bsu[eè]de\b|\bsu[eé]cia\b"),
    "noruega": ("Noruega", "Norway", "Noruega", "#EF2B2D", "#002868", r"\bnoruega\b|\bnorway\b|\bnorv[eè]ge\b"),
    "turquia": ("Turquía", "Turkey", "Turquia", "#E30A17", "#FFFFFF", r"\bturqu[ií]a\b|\bturkey\b|\bturquie\b"),
    "ecuador": ("Ecuador", "Ecuador", "Equador", "#FFDD00", "#034EA2", r"\becuador\b|\b[eé]quateur\b"),
    "chile": ("Chile", "Chile", "Chile", "#D52B1E", "#FFFFFF", r"\bchile\b"),
    "peru": ("Perú", "Peru", "Peru", "#D91023", "#FFFFFF", r"\bper[uú]\b"),
    "mexico": ("México", "Mexico", "México", "#006847", "#FFFFFF", r"\bm[eé]xico\b|\bmexico\b"),
    "estadosunidos": ("Estados Unidos", "United States", "Estados Unidos", "#B22234", "#3C3B6E", r"\bestados unidos\b|\busa\b|\bunited states\b|\b[eé]tats-unis\b"),
    "japon": ("Japón", "Japan", "Japão", "#BC002D", "#FFFFFF", r"\bjap[oó]n\b|\bjapan\b"),
    "coreadelsur": ("Corea del Sur", "South Korea", "Coreia do Sul", "#C60C30", "#FFFFFF", r"corea del sur|\bsouth korea\b|cor[eé]e du sud"),
    "marruecos": ("Marruecos", "Morocco", "Marrocos", "#C1272D", "#006233", r"\bmarruecos\b|\bmorocco\b|\bmaroc\b"),
    "senegal": ("Senegal", "Senegal", "Senegal", "#00853F", "#FDEF42", r"\bsenegal\b|\bs[eé]n[eé]gal\b"),
    "nigeria": ("Nigeria", "Nigeria", "Nigéria", "#008751", "#FFFFFF", r"\bnigeria\b|\bnig[eé]ria\b"),
    "arabiasaudita": ("Arabia Saudita", "Saudi Arabia", "Arábia Saudita", "#006C35", "#FFFFFF", r"arabia saudita|saudi arabia|arabie saoudite"),
    "australia": ("Australia", "Australia", "Austrália", "#00843D", "#FFCD00", r"\baustralia\b|\baustr[aá]lia\b"),
    "ucrania": ("Ucrania", "Ukraine", "Ucrânia", "#0057B7", "#FFD700", r"\bucrania\b|\bukraine\b|\bucr[aâ]nia\b"),
    # South American clubs
    "flamengo": ("Flamengo", "Flamengo", "Flamengo", "#E30613", "#000000", r"\bflamengo\b"),
    "palmeiras": ("Palmeiras", "Palmeiras", "Palmeiras", "#006437", "#FFFFFF", r"\bpalmeiras\b"),
    "corinthians": ("Corinthians", "Corinthians", "Corinthians", "#000000", "#FFFFFF", r"\bcorinthians\b"),
    "saopaulo": ("São Paulo FC", "São Paulo FC", "São Paulo FC", "#FE0000", "#000000", r"s[aã]o paulo"),
    "santos": ("Santos FC", "Santos FC", "Santos FC", "#FFFFFF", "#000000", r"\bsantos\b"),
    "gremio": ("Grêmio", "Grêmio", "Grêmio", "#0D80C4", "#000000", r"\bgr[eê]mio\b"),
    "internacional": ("Internacional", "Internacional", "Internacional", "#D2001C", "#FFFFFF", r"\binternacional\b|\bsc internacional\b"),
    "penarol": ("Peñarol", "Peñarol", "Peñarol", "#FFD100", "#000000", r"pe[nñ]arol"),
    "nacional": ("Club Nacional de Football", "Nacional (Uruguay)", "Nacional (Uruguai)", "#FFFFFF", "#1E3A8A", r"club nacional de football|nacional de montevideo"),
    "colocolo": ("Colo-Colo", "Colo-Colo", "Colo-Colo", "#FFFFFF", "#000000", r"colo-?colo"),
}
