BATCH6 = {
    # --- Missing Big-5 league clubs (2025/26 rosters) ---
    "burnley": ("Burnley FC", "Burnley FC", "Burnley FC", "#6C1D45", "#99D6EA", r"\bburnley\b"),
    "heidenheim": ("1. FC Heidenheim", "1. FC Heidenheim", "1. FC Heidenheim", "#E2001A", "#002856", r"heidenheim"),
    "auxerre": ("AJ Auxerre", "AJ Auxerre", "AJ Auxerre", "#FFFFFF", "#002F6C", r"\bauxerre\b"),
    "angers": ("Angers SCO", "Angers SCO", "Angers SCO", "#000000", "#FFFFFF", r"\bangers\b"),
    "lehavre": ("Le Havre AC", "Le Havre AC", "Le Havre AC", "#00AEEF", "#001E62", r"le havre"),
    "parisfc": ("Paris FC", "Paris FC", "Paris FC", "#001E62", "#ED1C24", r"\bparis fc\b"),
    "cagliari": ("Cagliari Calcio", "Cagliari Calcio", "Cagliari Calcio", "#8B1E3F", "#002F6C", r"\bcagliari\b"),
    "cremonese": ("US Cremonese", "US Cremonese", "US Cremonese", "#8B8B8B", "#CC0000", r"\bcremonese\b"),
    "hellasverona": ("Hellas Verona", "Hellas Verona", "Hellas Verona", "#FFD700", "#002F6C", r"hellas verona"),
    "lecce": ("US Lecce", "US Lecce", "US Lecce", "#FFD700", "#CC0000", r"\blecce\b"),
    "parmacalcio": ("Parma Calcio", "Parma Calcio", "Parma Calcio", "#FFD700", "#002F6C", r"\bparma\b"),
    "pisa": ("Pisa Sporting Club", "Pisa Sporting Club", "Pisa Sporting Club", "#002F6C", "#FFFFFF", r"\bpisa\b"),
    "sassuolo": ("US Sassuolo", "US Sassuolo", "US Sassuolo", "#000000", "#00693E", r"\bsassuolo\b"),

    # --- Missing national teams (curated by commercial relevance, not
    # every FIFA member — colors are a best-effort approximation, to be
    # confirmed by photo like every other pick during mining) ---
    "paraguay": ("Paraguay", "Paraguay", "Paraguai", "#DA121A", "#FFFFFF", r"\bparaguay\b"),
    "bolivia": ("Bolivia", "Bolivia", "Bolívia", "#007934", "#FFFFFF", r"\bbolivia\b|\bbol[ií]via\b"),
    "canada": ("Canadá", "Canada", "Canadá", "#FF0000", "#FFFFFF", r"\bcanad[aá]\b"),
    "honduras": ("Honduras", "Honduras", "Honduras", "#00287A", "#FFFFFF", r"\bhonduras\b"),
    "elsalvador": ("El Salvador", "El Salvador", "El Salvador", "#0047AB", "#FFFFFF", r"\bel salvador\b"),
    "guatemala": ("Guatemala", "Guatemala", "Guatemala", "#4997D0", "#FFFFFF", r"\bguatemala\b"),
    "trinidadytobago": ("Trinidad y Tobago", "Trinidad and Tobago", "Trinidad e Tobago", "#DA291C", "#000000", r"trinidad (y|and|e) tobago"),
    "romania": ("Rumania", "Romania", "Rom[eê]nia", "#FFD700", "#002868", r"\brumania\b|\bromania\b|\brom[eê]nia\b"),
    "chequia": ("Chequia", "Czech Republic", "Rep[uú]blica Tcheca", "#D7141A", "#FFFFFF", r"\bchequia\b|czech republic|rep[uú]blica tcheca|\bczechia\b"),
    "eslovaquia": ("Eslovaquia", "Slovakia", "Eslov[aá]quia", "#0B4EA2", "#FFFFFF", r"\beslovaquia\b|\bslovakia\b|\beslov[aá]quia\b"),
    "eslovenia": ("Eslovenia", "Slovenia", "Eslov[eê]nia", "#FFFFFF", "#00A651", r"\beslovenia\b|\bslovenia\b|\beslov[eê]nia\b"),
    "finlandia": ("Finlandia", "Finland", "Finl[aâ]ndia", "#FFFFFF", "#003580", r"\bfinlandia\b|\bfinland\b|\bfinl[aâ]ndia\b"),
    "bosnia": ("Bosnia", "Bosnia and Herzegovina", "B[oó]snia", "#002F6C", "#FFCD00", r"\bbosnia\b"),
    "albania": ("Albania", "Albania", "Alb[aâ]nia", "#E41E20", "#000000", r"\balbania\b|\balb[aâ]nia\b"),
    "georgia": ("Georgia", "Georgia", "Ge[oó]rgia", "#FFFFFF", "#FF0000", r"\bgeorgia\b|\bge[oó]rgia\b"),
    "macedoniadelnorte": ("Macedonia del Norte", "North Macedonia", "Maced[oô]nia do Norte", "#D20000", "#FFD700", r"macedonia del norte|north macedonia|maced[oô]nia do norte"),
    "israel": ("Israel", "Israel", "Israel", "#FFFFFF", "#0038B8", r"\bisrael\b"),
    "bulgaria": ("Bulgaria", "Bulgaria", "Bulg[aá]ria", "#00966E", "#FFFFFF", r"\bbulgaria\b|\bbulg[aá]ria\b"),
    "iraq": ("Irak", "Iraq", "Iraque", "#FFFFFF", "#CE1126", r"\birak\b|\biraq\b|\biraque\b"),
    "uzbekistan": ("Uzbekistán", "Uzbekistan", "Uzbequist[aã]o", "#FFFFFF", "#0099CC", r"uzbekist[aá]n|uzbekistan|uzbequist[aã]o"),
    "jordania": ("Jordania", "Jordan", "Jord[aâ]nia", "#FFFFFF", "#CE1126", r"\bjordania\b|\bjordan\b|\bjord[aâ]nia\b"),
    "india": ("India", "India", "[IÍ]ndia", "#1D4491", "#FF9933", r"\bindia\b|\b[ií]ndia\b"),
    "indonesia": ("Indonesia", "Indonesia", "Indon[eé]sia", "#E4032E", "#FFFFFF", r"\bindonesia\b|\bindon[eé]sia\b"),
    "vietnam": ("Vietnam", "Vietnam", "Vietn[aã]", "#DA251D", "#FFD700", r"\bvietnam\b|\bviet nam\b|\bvietn[aã]\b"),
    "tailandia": ("Tailandia", "Thailand", "Tail[aâ]ndia", "#A51931", "#FFFFFF", r"\btailandia\b|\bthailand\b|\btail[aâ]ndia\b"),
    "mali": ("Malí", "Mali", "Mali", "#14B53A", "#FCD116", r"\bmal[ií]\b"),
    "burkinafaso": ("Burkina Faso", "Burkina Faso", "Burkina Faso", "#009639", "#FCD116", r"burkina faso"),
    "caboverde": ("Cabo Verde", "Cape Verde", "Cabo Verde", "#003893", "#FFFFFF", r"cabo verde|cape verde"),
    "zambia": ("Zambia", "Zambia", "Z[aâ]mbia", "#198A00", "#FF8200", r"\bzambia\b|\bz[aâ]mbia\b"),
    "gabon": ("Gabón", "Gabon", "Gab[aã]o", "#009E60", "#FCD116", r"\bgab[oó]n\b|\bgabon\b|\bgab[aã]o\b"),
}
