BATCH3 = {
    # Eredivisie
    "ajax": ("Ajax", "Ajax", "Ajax", "#D2122E", "#FFFFFF", r"\bajax\b"),
    "psveindhoven": ("PSV Eindhoven", "PSV Eindhoven", "PSV Eindhoven", "#ED1C24", "#FFFFFF", r"\bpsv\b"),
    "feyenoord": ("Feyenoord", "Feyenoord", "Feyenoord", "#FF0000", "#FFFFFF", r"\bfeyenoord\b"),
    # Primeira Liga
    "porto": ("FC Porto", "FC Porto", "FC Porto", "#003C7D", "#FFFFFF", r"\bfc porto\b|\bporto\b"),
    "benfica": ("SL Benfica", "SL Benfica", "SL Benfica", "#E30613", "#FFFFFF", r"\bbenfica\b"),
    "sportingcp": ("Sporting CP", "Sporting CP", "Sporting CP", "#008542", "#FFFFFF", r"sporting (cp|clube de portugal|lisbon|lisboa)"),
    "braga": ("SC Braga", "SC Braga", "SC Braga", "#DC052D", "#FFFFFF", r"\bsc braga\b|\bbraga\b"),
    # Scottish Premiership
    "celtic": ("Celtic FC", "Celtic FC", "Celtic FC", "#018749", "#FFFFFF", r"\bceltic\b"),
    "rangers": ("Rangers FC", "Rangers FC", "Rangers FC", "#1D3E7C", "#FFFFFF", r"\brangers\b"),
    # MLS
    "intermiami": ("Inter Miami CF", "Inter Miami CF", "Inter Miami CF", "#F7B5CD", "#231F20", r"inter miami"),
    "lagalaxy": ("LA Galaxy", "LA Galaxy", "LA Galaxy", "#00245D", "#FFD200", r"\bla galaxy\b"),
    # Liga MX
    "clubamerica": ("Club América", "Club América", "Club América", "#FFD700", "#00296B", r"club am[eé]rica"),
    "chivas": ("Chivas Guadalajara", "Chivas Guadalajara", "Chivas Guadalajara", "#A6192E", "#003DA5", r"\bchivas\b|guadalajara"),
    "cruzazul": ("Cruz Azul", "Cruz Azul", "Cruz Azul", "#0033A0", "#FFFFFF", r"cruz azul"),
    "tigresuanl": ("Tigres UANL", "Tigres UANL", "Tigres UANL", "#FDB913", "#00447C", r"\btigres\b"),
    "monterrey": ("CF Monterrey", "CF Monterrey", "CF Monterrey", "#003DA5", "#FFFFFF", r"\bmonterrey\b"),
    # More Argentine clubs
    "racingclub": ("Racing Club", "Racing Club", "Racing Club", "#87CEFA", "#FFFFFF", r"racing club"),
    "sanlorenzo": ("San Lorenzo", "San Lorenzo", "San Lorenzo", "#0D2B52", "#E0201B", r"san lorenzo"),
    "velez": ("Vélez Sarsfield", "Vélez Sarsfield", "Vélez Sarsfield", "#FFFFFF", "#003DA5", r"v[eé]lez sarsfield|v[eé]lez"),
    "estudiantes": ("Estudiantes de La Plata", "Estudiantes de La Plata", "Estudiantes de La Plata", "#D2001C", "#FFFFFF", r"estudiantes de la plata"),
    # More Brazilian clubs
    "cruzeiro": ("Cruzeiro", "Cruzeiro", "Cruzeiro", "#003DA5", "#FFFFFF", r"\bcruzeiro\b"),
    "atleticomineiro": ("Atlético Mineiro", "Atlético Mineiro", "Atlético Mineiro", "#000000", "#FFFFFF", r"atl[eé]tico mineiro|\bgal[oo]\b"),
    "botafogo": ("Botafogo", "Botafogo", "Botafogo", "#000000", "#FFFFFF", r"\bbotafogo\b"),
    "vascodagama": ("Vasco da Gama", "Vasco da Gama", "Vasco da Gama", "#000000", "#FFFFFF", r"vasco da gama"),
    "fluminense": ("Fluminense", "Fluminense", "Fluminense", "#870619", "#006B3D", r"\bfluminense\b"),
    # More national teams
    "egipto": ("Egipto", "Egypt", "Egito", "#CE1126", "#000000", r"\begipto\b|\begypt\b|\b[eé]gypte\b"),
    "ghana": ("Ghana", "Ghana", "Gana", "#CE1126", "#FCD116", r"\bghana\b"),
    "argelia": ("Argelia", "Algeria", "Argélia", "#006233", "#FFFFFF", r"\bargelia\b|\balgeria\b|\balg[eé]rie\b"),
    "tunez": ("Túnez", "Tunisia", "Tunísia", "#E70013", "#FFFFFF", r"\bt[uú]nez\b|\btunisia\b|\btunisie\b"),
    "camerun": ("Camerún", "Cameroon", "Camarões", "#007A5E", "#CE1126", r"camer[uú]n|\bcameroon\b|\bcameroun\b"),
    "costamarfil": ("Costa de Marfil", "Ivory Coast", "Costa do Marfim", "#F77F00", "#FFFFFF", r"costa de marfil|ivory coast|c[oô]te d.ivoire"),
    "austria": ("Austria", "Austria", "Áustria", "#ED2939", "#FFFFFF", r"\baustria\b|\b[aá]ustria\b"),
    "irlanda": ("Irlanda", "Republic of Ireland", "Irlanda", "#169B62", "#FFFFFF", r"\birlanda\b|\bireland\b|\birlande\b"),
    "islandia": ("Islandia", "Iceland", "Islândia", "#02529C", "#FFFFFF", r"\bislandia\b|\biceland\b|\bisland[eê]"),
    "serbia": ("Serbia", "Serbia", "Sérvia", "#C6363C", "#FFFFFF", r"\bserbia\b|\bs[eé]rvia\b"),
    "qatar": ("Catar", "Qatar", "Catar", "#8D1B3D", "#FFFFFF", r"\bcatar\b|\bqatar\b"),
    "iran": ("Irán", "Iran", "Irã", "#239F40", "#DA0000", r"\bir[aá]n\b"),
    "emiratosarabes": ("Emiratos Árabes Unidos", "United Arab Emirates", "Emirados Árabes Unidos", "#00732F", "#FFFFFF", r"emiratos [aá]rabes|united arab emirates|[eé]mirats arabes"),
    "china": ("China", "China", "China", "#DE2910", "#FFDE00", r"\bchina\b"),
    "nuevazelanda": ("Nueva Zelanda", "New Zealand", "Nova Zelândia", "#000000", "#FFFFFF", r"nueva zelanda|new zealand|nouvelle-z[eé]lande"),
    "costarica": ("Costa Rica", "Costa Rica", "Costa Rica", "#002B7F", "#CE1126", r"costa rica"),
    "jamaica": ("Jamaica", "Jamaica", "Jamaica", "#009B3A", "#FED100", r"\bjamaica\b"),
    "panama": ("Panamá", "Panama", "Panamá", "#DA121A", "#072357", r"\bpanam[aá]\b"),
    "irlandadelnorte": ("Irlanda del Norte", "Northern Ireland", "Irlanda do Norte", "#00693E", "#FFFFFF", r"irlanda del norte|irlanda do norte|northern ireland|irlande du nord"),
    "sudafrica": ("Sudáfrica", "South Africa", "África do Sul", "#FFB81C", "#007A4D", r"\bsud[aá]frica\b|\bsouth africa\b|afrique du sud"),
    "grecia": ("Grecia", "Greece", "Grécia", "#0D5EAF", "#FFFFFF", r"\bgrecia\b|\bgreece\b|\bgr[eè]ce\b|\bgr[eé]cia\b"),
    "haiti": ("Haití", "Haiti", "Haiti", "#00209F", "#D21034", r"\bhait[ií]\b|\bhaiti\b|\bha[iï]ti\b"),
    "hungria": ("Hungría", "Hungary", "Hungria", "#CE2939", "#FFFFFF", r"\bhungr[ií]a\b|\bhungary\b|\bhongrie\b|\bhungria\b"),
    "rdcongo": ("RD Congo", "DR Congo", "RD Congo", "#007FFF", "#CE1021", r"\brd congo\b|\bdr congo\b|\bcongo rd\b"),
    "venezuela": ("Venezuela", "Venezuela", "Venezuela", "#7B1E3A", "#FFFFFF", r"\bvenezuela\b"),
}
